version: '3'

services:
  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=1000M
    volumes:
      - ./db/mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

